### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by remsk** [dissidiadb/v2#23]
- [x] Write commands list post on Patreon
- [x] Add BT default effects
- [x] Remove Eald dupe BT effect
- [x] Add secondary OK BT default effect
- [x] Same ID auras must not be taken into account
- [x] Change BT+ effect icon
- [x] Change icons ON cmd list
- [x] List all current issues in a separate post
- [x] Update ailment list with Prishe data update
- [x] Publish everything
- [x] Sleep
